Hous-Release/hous-server

- src/main/java/hous/server/service/badge/BadgeService.java
- src/main/java/hous/server/service/room/RoomService.java
- src/main/java/hous/server/service/rule/RuleService.java
- src/main/java/hous/server/service/todo/TodoScheduledService.java
- src/main/java/hous/server/service/todo/TodoService.java
- src/main/java/hous/server/service/user/UserService.java
- Closes #104
1. 스케줄 서비스, 배지 획득 로직 리팩토링
> 스케줄 서비스, 배지 획득 로직 리팩토링

- src/main/java/hous/server/domain/badge/BadgeInfo.java
- Closes #110 
1. 배지 설명 문구 수정
- 역대급 초초초초초초초간단 pr
> #110 [fix] 배지 설명 문구 수정

- src/main/java/hous/server/domain/notification/PushMessage.java
- src/main/java/hous/server/service/notification/NotificationService.java
- src/main/java/hous/server/service/todo/TodoScheduledService.java
- src/main/java/hous/server/service/todo/TodoService.java
- Closes #113
1. 새로운 todo 추가 푸시알림 구현
2. 오늘의 todo 시작 푸시알림 구현
3. 미완료 todo 알림 푸시알림 구현
> todo 관련 푸시알림 구현

- src/main/java/hous/server/controller/user/UserController.java
- src/main/java/hous/server/domain/user/Setting.java
- src/main/java/hous/server/service/user/UserService.java
- src/main/java/hous/server/service/user/UserServiceUtils.java
- src/main/java/hous/server/service/user/dto/request/UpdatePushSettingRequestDto.java
- Closes #118
1. PATCH 메소드로 수정
> #118 [fix] 푸시 알림 설정 수정 기능 PATCH 메소드로 수정

- src/main/java/hous/server/common/success/SuccessCode.java
- src/main/java/hous/server/controller/user/UserController.java
- src/main/java/hous/server/service/room/RoomService.java
- src/main/java/hous/server/service/user/UserService.java
- Closes #119
1. 피드백 한걸음 뱃지 api 구현
> 피드백 한걸음 뱃지 api 구현

- src/main/java/hous/server/controller/advice/ControllerExceptionAdvice.java
- Closes #124 
1. ControllerExceptionAdvice 에서 모든 Exception 을 error level 로 로그 출력하던 것을
400 번대 warn 레벨, 500 번대 error 레벨로 수정합니다.
> #124 [fix] 로그 레벨 분리

- src/main/java/hous/server/domain/user/repository/UserRepositoryCustom.java
- src/main/java/hous/server/domain/user/repository/UserRepositoryImpl.java
- src/main/java/hous/server/service/user/UserScheduledService.java
- Closes #122 
1. 호미의 탄생 배지 구현
> 호미의 탄생 배지 구현

- src/main/java/hous/server/service/firebase/FirebaseCloudMessageService.java
- src/main/java/hous/server/service/notification/NotificationService.java
- src/main/java/hous/server/service/user/UserServiceUtils.java
- Closes #131
1. fcmToken null 인 경우 에러 해결
- sendMessageTo 인자 fcmToken -> User
- querydsl findUserByFcmToken 수정
> #131 [fix] fcmToken null 인 경우 에러 해결

- src/main/java/hous/server/common/exception/UnAuthorizedException.java
- src/main/java/hous/server/external/client/apple/AppleTokenProviderImpl.java
- Closes #133
1. 애플 로그인 에러 핸들링 추가
> #133 [fix] 애플 로그인 에러 핸들링 추가

- .github/workflows/deploy.yml
- .github/workflows/pr-check.yml
- .gitignore
- build.gradle
- scripts/deploy.sh
- src/main/resources/console-appender.xml
- src/main/resources/file-error-appender.xml
- src/main/resources/file-info-appender.xml
- src/main/resources/file-warn-appender.xml
- src/main/resources/logback-spring.xml
- Closes #126
1. 로그 파일 생성 관련 설정 파일 추가하였습니다. 
- 음 ... jar 파일 실행해서 log 디렉터리 생기는 것은 확인했습니다!
- 요청하신대로 error는 error만, warn은 warn만 그 외 info 이상은 일반으로 들어가도록 해두습니다.
- 참고자료 [우테코](https://livenow14.tistory.com/64)
> 로그 설정 파일 추가

- src/main/java/hous/server/domain/badge/Badge.java
- src/main/java/hous/server/domain/badge/BadgeInfo.java
- src/main/java/hous/server/service/user/dto/response/MyBadgeInfoResponse.java
- src/main/java/hous/server/service/user/dto/response/RepresentBadgeInfo.java
- src/main/java/hous/server/service/user/dto/response/UserInfoResponse.java
- Closes #143 
1. 배지 테이블, enum 수정
> #143 [fix] 배지 테이블, enum 수정

- src/main/java/hous/server/config/scheduler/SchedulerConfig.java
- src/main/java/hous/server/config/scheduler/SchedulerErrorHandler.java
- Closes #147
1. 스케줄러 관련 에러 핸들링 추가
> #147 [fix] 스케줄러 관련 에러 핸들링 추가

- src/main/java/hous/server/service/notification/NotificationService.java
- Closes #151 
1. 알림 content enum name으로 저장되는 오류 수정
- 머쓱한 실수..
> #151 [fix] 알림 content enum name으로 저장되는 오류 수정

- .github/workflows/deploy.yml
- .github/workflows/pr-check.yml
- .gitignore
- build.gradle
- src/main/java/hous/server/common/util/JwtUtils.java
- src/main/java/hous/server/controller/advice/ControllerExceptionAdvice.java
- src/main/java/hous/server/service/slack/SlackService.java
- Closes #128
1. slack 알림 에러 추가
- 마지막 커밋에 지난 PR에 남겨주신 리뷰 반영했습니다!
> slack 알림 에러 추가

- src/main/java/hous/server/service/home/HomeRetrieveService.java
- src/main/java/hous/server/service/home/dto/response/HomeInfoResponse.java
- Closes #156 
1. 홈 조회에 room code 정보 추가
> #156 [fix] 홈 조회에 room code 정보 추가

- src/main/java/hous/server/service/home/HomeRetrieveService.java
- src/main/java/hous/server/service/home/dto/response/HomeInfoResponse.java
- src/main/java/hous/server/service/todo/TodoRetrieveService.java
- src/main/java/hous/server/service/todo/dto/response/DayOfWeekTodo.java
- src/main/java/hous/server/service/todo/dto/response/TodoAllDayResponse.java
- src/main/java/hous/server/service/todo/dto/response/TodoDetailInfo.java
- src/main/java/hous/server/service/todo/dto/response/TodoInfo.java
- src/main/java/hous/server/service/todo/dto/response/TodoMainResponse.java
- Closes #158
1. 클라 요청에 따라 멤버별 조회 시 todoId도 받도록 수정했습니다.
- 기존의 MyTodo 클래스 재사용을 위해 TodoInfo로 네이밍 수정했습니다!
> 멤버별 조회 시 todoId도 받도록 수정

- src/main/java/hous/server/controller/auth/AuthController.java
- src/main/java/hous/server/controller/auth/dto/response/LoginResponse.java
- src/main/java/hous/server/service/room/RoomService.java
- Closes #160
1. 클라 요청에 따라 로그인 요청 시 방 참가여부 함께 전달하도록 수정하였습니다!
- commonAuthService에서 진행했는데 피드백 부탁드립니다. 혼내주십쇼.
> 클라 요청에 따라 로그인 요청 시 방 참가여부 함께 전달하도록 수정

- src/main/java/hous/server/controller/user/UserRetrieveController.java
- src/main/java/hous/server/domain/badge/Acquire.java
- src/main/java/hous/server/service/user/UserRetrieveService.java
- src/main/java/hous/server/service/user/dto/response/MyBadgeInfoResponse.java
- Closes #162
1. 신규 배지 표시, 읽음 처리 추가
> #162 [fix] 신규 배지 표시, 읽음 처리 추가

- src/main/java/hous/server/service/todo/TodoRetrieveService.java
- Closes #167
1. 방 퇴사할 때 나의 Todo 필터링 추가
> #167 [fix] 방 퇴사할 때 나의 Todo 필터링 추가

- src/main/java/hous/server/controller/auth/AuthController.java
- src/main/java/hous/server/service/auth/CreateTokenService.java
- src/main/java/hous/server/service/auth/dto/response/RefreshResponse.java
- Closes #172
1. token 정보 객체에 포함
2. isJoiningRoom 데이터 추가
-
> #172 [fix] 토큰 갱신 응답 수정

- .github/workflows/deploy.yml
- .github/workflows/pr-check.yml
- src/main/java/hous/server/service/room/RoomService.java
- Closes #174 
1. 슬랙 알림, 방 퇴사 500 에러 해결
> 슬랙 알림, 방 퇴사 500 에러 해결

- src/main/java/hous/server/common/exception/ErrorCode.java
- src/main/java/hous/server/controller/auth/AuthController.java
- src/main/java/hous/server/service/auth/AuthService.java
- src/main/java/hous/server/service/auth/impl/AppleAuthService.java
- src/main/java/hous/server/service/auth/impl/KakaoAuthService.java
- src/main/java/hous/server/service/user/UserService.java
- src/main/java/hous/server/service/user/UserServiceUtils.java
- Closes #176
1. 강제 로그인 api 추가
> #176 [feat] 강제 로그인 api 추가

- src/main/java/hous/server/controller/todo/TodoRetrieveController.java
- src/main/java/hous/server/controller/user/UserController.java
- src/main/java/hous/server/service/room/RoomService.java
- src/main/java/hous/server/service/room/RoomServiceUtils.java
- src/main/java/hous/server/service/user/UserService.java
- Closes #166
1. 기존 방식은 탈퇴는 무조건 방에 참여한 경우에만 가능하도록 구현했습니다.
2. 기획 변경에 따라 온보딩 뷰에서도 삭제 가능하도록 수정하였습니다. `if(room!=null)`
- 공통으로 사용되는 로직을 함수로 변경했는데 네이밍 지적 부탁드립니다 ^&^ ..
> 사용자 탈퇴 방 참여 여부에 따라 다르게 수정

- src/main/java/hous/server/controller/auth/AuthController.java
- src/main/java/hous/server/service/auth/CommonAuthService.java
- src/main/java/hous/server/service/auth/CommonAuthServiceUtils.java
- src/main/java/hous/server/service/auth/impl/AppleAuthService.java
- src/main/java/hous/server/service/auth/impl/KakaoAuthService.java
- Closes #177 
1. 로그아웃 방에 참여하지 않아도 가능하도록 수정
2. auth 관련 공통 로직 모듈화
> 로그인 로직 리팩토링, 로그아웃 로직 수정

- src/main/java/hous/server/controller/auth/AuthController.java
- src/main/java/hous/server/service/slack/SlackService.java
- Closes #180
1. 슬랙 500에러 알림 여부 확인 테스트
> #180 [fix] 슬랙 500에러 알림 여부 확인 테스트

- .github/workflows/deploy.yml
- .github/workflows/pr-check.yml
- src/main/java/hous/server/service/slack/SlackService.java
- Closes #180
1. application.properties -> yml 로 수정
> #180 [fix] application.properties -> yml 로 수정

- src/main/java/hous/server/common/util/JwtUtils.java
- Closes #189 
1. JWT 관련 에러 핸들링 추가했습니다.
> #189 [fix] JWT 관련 에러 핸들링 추가

- src/main/java/hous/server/common/success/SuccessCode.java
- src/main/java/hous/server/controller/user/UserRetrieveController.java
- src/main/java/hous/server/service/user/UserRetrieveService.java
- src/main/java/hous/server/service/user/dto/response/PushSettingResponse.java
- Closes #197
1. 푸시 알림 설정 정보 조회 api 구현
> #197 [feat] 푸시 알림 설정 정보 조회 api 구현

- src/main/java/hous/server/domain/room/Room.java
- src/main/java/hous/server/service/todo/TodoService.java
- src/main/java/hous/server/service/todo/TodoServiceUtils.java
- Closes #199
1. Set 자료구조 사용해서 중복 조회 해결했습니다.
2. updateTodo 부분에 Room 관련 업데이트 빠졌던 것 추가했습니다.
> todo 중복 조회 이슈 해결

- src/main/java/hous/server/service/room/RoomService.java
- src/main/java/hous/server/service/room/RoomServiceUtils.java
- src/main/java/hous/server/service/user/UserService.java
> #201 [fix] 방 퇴사 로직 수정

- src/main/java/hous/server/service/auth/CommonAuthService.java
- src/main/java/hous/server/service/auth/CommonAuthServiceUtils.java
- src/main/java/hous/server/service/auth/impl/AppleAuthService.java
- src/main/java/hous/server/service/auth/impl/KakaoAuthService.java
- Closes #209
1. 로그인 fcmToken 중복 관련 트랜잭션 이슈 해결
> #209 [fix] 로그인 fcmToken 중복 관련 트랜잭션 이슈 해결

- src/main/java/hous/server/service/auth/impl/AppleAuthService.java
- src/main/java/hous/server/service/auth/impl/KakaoAuthService.java
- Closes #216
1. 회원가입시 fcmToken 중복 관련 이슈 해결
> #216 [fix] 회원가입시 fcmToken 중복 관련 이슈 해결

- src/main/java/hous/server/controller/user/UserRetrieveController.java
- src/main/java/hous/server/domain/badge/BadgeInfo.java
- src/main/java/hous/server/service/home/dto/response/HomeInfoResponse.java
- src/main/java/hous/server/service/rule/RuleService.java
- src/main/java/hous/server/service/todo/TodoRetrieveService.java
- src/main/java/hous/server/service/todo/TodoService.java
- src/main/java/hous/server/service/todo/TodoServiceUtils.java
- src/main/java/hous/server/service/todo/dto/response/TodoInfoResponse.java
- src/main/java/hous/server/service/todo/dto/response/UserPersonalityInfoResponse.java
- src/main/java/hous/server/service/user/UserRetrieveService.java
- src/main/java/hous/server/service/user/UserServiceUtils.java
- Closes #227
1. homieId -> onboardingId로 통일했습니다.
2. 갑분 리팩토링을 진행했습니다.
- List<Todo>[] -> Map<Integer, Set<Todo>> 로 변경
- Intstream -> fori로 변경
- Intstream으로 foreach를 도는게 살짝 불편하신 것 같아 fori로 변경
> homieId -> onboardingId로 통일

- src/main/java/hous/server/domain/badge/BadgeInfo.java
- Closes #225
1. 푸시 알림 워딩 집 Rules -> 첫 Rules로 변경
> #225 [fix] 푸시 알림 워딩 집 Rules -> 첫 Rules로 변경

- src/main/java/hous/server/domain/user/Onboarding.java
- src/main/java/hous/server/service/todo/TodoServiceUtils.java
- Closes #229
1. updateUserInfo introduction null인 경우 고려
> #229 [fix] updateUserInfo introduction null인 경우 고려

- src/main/java/hous/server/controller/advice/ControllerExceptionAdvice.java
- src/main/java/hous/server/controller/user/UserController.java
- src/main/java/hous/server/service/slack/SlackService.java
- src/main/java/hous/server/service/slack/SlackServiceUtils.java
- src/main/java/hous/server/service/slack/dto/response/UserDelete.java
- src/main/java/hous/server/service/slack/dto/response/UserDeleteResponse.java
- src/main/java/hous/server/service/user/UserRetrieveService.java
- Closes #536
1. 사용자 탈퇴 시 슬랙 알림 구현
2. serviceUtils로 분리했습니다. 지저분한 친구들은
> #231 [feat] 사용자 탈퇴 시 슬랙 알림 구현

- src/main/java/hous/server/controller/rule/RuleController.java
- src/main/java/hous/server/service/rule/RuleService.java
- Closes #234
1. 규칙 수정 시 규칙에 대한 validate 추가
- 규칙 추가 시에는 validate가 있는데 수정 시에는 없어서 추가했습니다!
> #234 [fix] 규칙 수정 시 규칙에 대한 validate 추가

- src/main/java/hous/server/service/notification/NotificationService.java
- src/main/java/hous/server/service/todo/TodoScheduledService.java
- src/main/java/hous/server/service/todo/TodoServiceUtils.java
- Closes #242
1. 생성한 todo의 알림 설정 여부도 추가
2. todo 9시, 10시 스케줄 시에도 todo의 알림 설정 여부 확인 하도록 추가 (뱃지 획득 시에는 안했습니다)
> #242 [fix] 생성한 todo의 알림 설정 여부도 추가

- src/main/java/hous/server/controller/rule/RuleController.java
- src/main/java/hous/server/service/rule/RuleService.java
- Closes #247
1. 이번 릴리즈 때 규칙 추가/수정 시 name 중복 여부는 없애기로 변경되어 주석처리
- 소혀니가 전화와서 요 부분 수정되었다고 해서 빠른 반영 갈겼습니다.
- 주석 추가 및 수정에 대한 컨벤션이 'comment'인 것 알고 계셨나요? ㅋㅋ ㅎㅎ ..
> #247 [comment] 이번 릴리즈 때 규칙 추가/수정 시 name 중복 여부는 없애기로 변경되어 주석처리

- build.gradle
- src/main/java/hous/server/common/aspect/PreventDuplicateRequest.java
- src/main/java/hous/server/common/aspect/RequestAspect.java
- src/main/java/hous/server/common/exception/ErrorCode.java
- src/main/java/hous/server/config/WebConfig.java
- src/main/java/hous/server/config/interceptor/auth/Auth.java
- src/main/java/hous/server/config/interceptor/auth/AuthInterceptor.java
- src/main/java/hous/server/config/interceptor/auth/LoginCheckHandler.java
- src/main/java/hous/server/config/interceptor/version/Version.java
- src/main/java/hous/server/config/interceptor/version/VersionCheckHandler.java
- src/main/java/hous/server/config/interceptor/version/VersionInterceptor.java
- src/main/java/hous/server/config/resolver/UserIdResolver.java
- src/main/java/hous/server/controller/auth/AuthController.java
- src/main/java/hous/server/controller/home/HomeRetrieveController.java
- src/main/java/hous/server/controller/room/RoomController.java
- src/main/java/hous/server/controller/room/RoomRetrieveController.java
- src/main/java/hous/server/controller/rule/RuleController.java
- src/main/java/hous/server/controller/rule/RuleRetrieveController.java
- src/main/java/hous/server/controller/todo/TodoController.java
- src/main/java/hous/server/controller/todo/TodoRetrieveController.java
- src/main/java/hous/server/controller/user/UserController.java
- src/main/java/hous/server/controller/user/UserRetrieveController.java
- src/main/java/hous/server/domain/common/RedisKey.java
- src/main/java/hous/server/service/todo/TodoService.java
- Closes #245
1. Redis를 이용하여 중복 요청 방지하는 AOP 로직 추가
- 고생했어유~!
> Redis를 이용하여 중복 요청 방지하는 로직 추가

- src/main/java/hous/server/service/room/RoomService.java
- src/main/java/hous/server/service/room/RoomServiceUtils.java
- Closes #249
1. 퇴사 로직 todo 및 방 퇴사 로직 수정, personality gray로 변경하도록 수정
> #249 [fix] 퇴사 로직 todo 및 방 퇴사 로직 수정, personality gray로 변경하도록 수정

- src/main/java/hous/server/common/aspect/RequestAspect.java
- Closes #252
1. AfterReturning -> After 로 수정
- https://deepweller.tistory.com/30
> #252 [fix] AfterReturning -> After 로 수정

- src/main/java/hous/server/controller/todo/TodoRetrieveController.java
- src/main/java/hous/server/service/todo/TodoRetrieveService.java
- src/main/java/hous/server/service/todo/dto/response/TodoAllDayInfo.java
- src/main/java/hous/server/service/todo/dto/response/TodoAllDayResponse.java
- src/main/java/hous/server/service/todo/dto/response/TodoAllMemberInfo.java
- src/main/java/hous/server/service/todo/dto/response/TodoAllMemberResponse.java
- Closes #256
1. Todo 멤버별, 요일별 조회에 방 총 todo 개수 필드 추가
> #256 [fix] Todo 멤버별, 요일별 조회에 방 총 todo 개수 필드 추가

- src/main/java/hous/server/service/room/RoomServiceUtils.java
- Closes #260
1. 방퇴사, 탈퇴시 나의 todo 삭제 관련 수정
> #260 [fix] 방퇴사, 탈퇴시 나의 todo 삭제 관련 수정

- build.gradle
- src/main/java/hous/server/service/todo/TodoScheduledService.java
- Closes #264
1. postgreSQL 사용하지 않아서 디펜던시에서 삭제했습니다
2. .size() != 0 을 isEmpty() 로 수정했습니다 ㅎㅎ .. 
- 괜찮쥬 ..?
> 사용하지 않는 디펜던시를 삭제하고, 자잘한 수정

- src/main/java/hous/server/config/WebConfig.java
- src/main/java/hous/server/controller/auth/AuthController.java
- src/main/java/hous/server/controller/home/HomeRetrieveController.java
- src/main/java/hous/server/controller/room/RoomController.java
- src/main/java/hous/server/controller/room/RoomRetrieveController.java
- src/main/java/hous/server/controller/rule/RuleController.java
- src/main/java/hous/server/controller/rule/RuleRetrieveController.java
- src/main/java/hous/server/controller/todo/TodoController.java
- src/main/java/hous/server/controller/todo/TodoRetrieveController.java
- src/main/java/hous/server/controller/user/UserController.java
- src/main/java/hous/server/controller/user/UserRetrieveController.java
- Closes #266
1. HealthController, VersionRetrieveController 제외한 모든 요청에 @Version 어노테이션 추가했습니다.
2. 426 상태코드에 대한 명세서도 반영했습니다.
- 헤더에 잘못된 형태의 HousOsType, HousVersion을 담을 경우 400에러가 나는데 이 경우에 대해서는 명세서 따로 추가하지 않았습니다.
- 이 부분은 슬랙 공지할 때 따로 설명할 예정입니다!
> 버전 관리 로직 반영

- src/main/java/hous/server/domain/user/Onboarding.java
- Closes #268
1. 자기소개 빈 값으로 변경할 경우, null 반영했습니다.
- if-else를 안쓰려고 저렇게 했는데 .... 괜찮나요 ... ? 뭐가 좋은 방법일지 잘 모르겠습니다 ㅠ ㅠ ㅠ 클린 코드는 어려워요.
> #268 [fix] 자기소개 빈 값으로 변경할 경우, null 반영

- .github/workflows/deploy-dev.yml
- .github/workflows/deploy-prod.yml
- .github/workflows/pr-check-dev.yml
- .github/workflows/pr-check-prod.yml
- Closes #262
1. prod 서버 배포용 yml 추가
> #262 [feat] prod 서버 배포용 yml 추가

- src/main/java/hous/server/controller/user/UserController.java
- src/main/java/hous/server/service/slack/SlackService.java
- src/main/java/hous/server/service/slack/SlackServiceUtils.java
- src/main/java/hous/server/service/slack/dto/response/UserDeleteResponse.java
- src/main/java/hous/server/service/user/UserRetrieveService.java
- src/main/java/hous/server/service/user/UserService.java
- Closes #271
1. 탈퇴 유저 알림 슬랙에 의견 추가
> #271 [fix] 탈퇴 유저 알림 슬랙에 의견 추가

- src/main/java/hous/server/domain/room/Room.java
- src/main/java/hous/server/service/room/RoomServiceUtils.java
- Closes #275 
1. 방장이 방을 나가면 방장이 다음 참여자로 바뀌도록 로직 수정
- UX 라이팅 수정 부분도 있는데, 이 부분은 쿼리 수정해서 노션에 반영할게요!
> #275 [!HOTFIX] 방장이 방을 나가면 방장이 다음 참여자로 바뀌도록 로직 수정

- src/main/java/hous/server/service/todo/TodoRetrieveService.java
- src/main/java/hous/server/service/todo/TodoServiceUtils.java
- Closes #286
1. todo 메인 조회, 멤버별 조회, 요일별 조회 이슈 해결
> #286 [!HOTFIX] todo 메인 조회, 멤버별 조회, 요일별 조회 이슈 해결

- docker-compose.yml
- src/main/java/hous/server/domain/room/Room.java
- src/main/java/hous/server/service/room/dto/request/SetRoomNameRequestDto.java
- src/main/java/hous/server/service/rule/RuleService.java
- src/main/java/hous/server/service/rule/RuleServiceUtils.java
- src/main/java/hous/server/service/rule/dto/request/CreateRuleRequestDto.java
- src/main/java/hous/server/service/todo/TodoRetrieveService.java
- src/main/java/hous/server/service/todo/TodoServiceUtils.java
- src/main/java/hous/server/service/todo/dto/request/TodoInfoRequestDto.java
- src/test/java/hous/server/service/rule/RuleServiceTest.java
- src/test/java/hous/server/service/todo/TodoServiceTest.java
- Closes #294
1. 동시에 Todo, Rule 추가 시 트랜잭션 이슈로 실패하는 문제 해결
- develop, main 에 머지하기 전에 db에 rulesCnt, todosCnt 칼럼 삭제해야해요!
- 제가 머지하면서 삭제하겠습니다~!
> 동시에 Todo, Rule 추가 시 트랜잭션 이슈로 실패하는 문제 해결

- src/main/java/hous/server/service/rule/RuleService.java
- src/main/java/hous/server/service/rule/RuleServiceUtils.java
- Closes #301
1. Rule 수정시 이름 중복 검사 로직 수정
> #301 [fix] Rule 수정시 이름 중복 검사 로직 수정

- src/main/java/hous/server/domain/badge/BadgeCounter.java
- src/main/java/hous/server/domain/badge/BadgeCounterListener.java
- src/main/java/hous/server/domain/badge/mongo/BadgeCounterRepository.java
- src/main/java/hous/server/domain/common/AuditingTimeEntity.java
- src/main/java/hous/server/domain/common/AutoIncrementSequence.java
- src/main/java/hous/server/domain/notification/NotificationListener.java
- src/main/java/hous/server/domain/notification/NotificationMongo.java
- src/main/java/hous/server/domain/notification/mongo/NotificationMongoRepository.java
- src/main/java/hous/server/service/mongodb/SequenceGeneratorService.java
- Closes #309 
1. Auto Increment 동작하기 위한 Sequence 컬렉션 추가 및 서비스 작성
2. NotificationMongo 컬렉션 추가 (Notification 때문에 임시 네이밍)
3. BadgeCounter 컬렉션 추가
- id 정상적으로 생성되는거 확인했는데 한가지 이슈가 있습니다.. createdAt 이 생성되지 않는 이슈인데요.. 찾아본 링크 공유드립니당..
https://stackoverflow.com/questions/35584271/spring-data-mongodb-annotation-createddate-isnt-working-when-id-is-assigned-m
- 위에 이슈 Listener 수정해서 해결했습니다!
- NotificationMongo 컬렉션은 로직 수정하고 Notification 테이블 삭제 후 Notification 으로 이름 수정하면 될 것 같아요~!
> MongoDB 컬렉션 설계

- docker-compose.yml
- src/main/java/hous/server/config/mongodb/MongoDbConfig.java
- src/test/java/hous/server/service/room/RoomServiceTest.java
- src/test/java/hous/server/service/rule/RuleServiceTest.java
- src/test/java/hous/server/service/todo/TodoServiceTest.java
- src/test/java/hous/server/service/user/UserServiceTest.java
- Closes #305
1. 테스트 코드 컨벤션 적용
2. MongoDB 트랜잭션 설정 삭제
- 테스트 코드 리팩토링 진행하려고 했는데 좀 논의 더 해보고 하면 좋을 것 같아서 우선 미뤄뒀습니다..
> 테스트코드 컨벤션 적용 및 MongoDB 설정 수정

- .github/workflows/api-deploy-dev.yml
- .github/workflows/api-deploy-prod.yml
- .github/workflows/api-pr-check-dev.yml
- .github/workflows/api-pr-check-prod.yml
- hous-api/build.gradle
- hous-api/src/main/java/hous/api/ApiApplication.java
- hous-api/src/main/java/hous/api/service/auth/impl/AppleAuthService.java
- hous-api/src/main/java/hous/api/service/auth/impl/KakaoAuthService.java
- hous-api/src/main/java/hous/api/service/firebase/FirebaseCloudMessageService.java
- hous-external/build.gradle
- hous-external/src/main/java/hous/external/client/apple/AppleApiClient.java
- hous-external/src/main/java/hous/external/client/apple/AppleTokenProvider.java
- hous-external/src/main/java/hous/external/client/apple/AppleTokenProviderImpl.java
- hous-external/src/main/java/hous/external/client/apple/dto/response/ApplePublicKeyResponse.java
- hous-external/src/main/java/hous/external/client/firebase/FirebaseApiClient.java
- hous-external/src/main/java/hous/external/client/kakao/KakaoApiClient.java
- hous-external/src/main/java/hous/external/client/kakao/dto/response/KakaoProfileResponse.java
- settings.gradle
- Closes #321
1. external api 호출 관련 모듈 분리
- 나중에 notification 서버 분리할 때 api 서버랑 의존성 없애기 위해서 external api 도 따로 모듈 분리했습니다!
> external api 모듈 분리
