src/main/java/hous/server/common/exception/ErrorCode.java, src/main/java/hous/server/controller/auth/AuthController.java, src/main/java/hous/server/domain/user/User.java, src/main/java/hous/server/service/auth/impl/AppleAuthService.java, src/main/java/hous/server/service/auth/impl/KaKaoAuthService.java, src/main/java/hous/server/service/user/UserService.java, src/main/java/hous/server/service/user/UserServiceUtils.java
- Closes #111
1. User 테이블 fcmToken 칼럼 (nullable = true, unique = true) 로 수정
2. 회원가입, 로그인 로직 fcmToken 중복 검사 로직 추가
- 로그아웃시 fcmToken null 처리하는 로직은 로그아웃 관련 이슈 파서 따로 진행하겠습니당
=> #111 [fix] User 테이블 수정 및 fcmToken 중복 검사 로직 추가

src/main/java/hous/server/controller/auth/AuthController.java, src/main/java/hous/server/controller/rule/RuleController.java, src/main/java/hous/server/domain/user/User.java, src/main/java/hous/server/service/auth/AuthServiceProvider.java, src/main/java/hous/server/service/auth/CommonAuthService.java, src/main/java/hous/server/service/auth/CreateTokenService.java, src/main/java/hous/server/service/auth/impl/KakaoAuthService.java, src/main/java/hous/server/service/firebase/FirebaseCloudMessageService.java
- Closes #117 
1. 로그아웃 api 추가
2. 서비스 내부 로그아웃 로직에 fcmToken null 처리, refresh token 만료 처리 추가
- social 로그인별로 구별하기 위해 AuthServiceImpl 이 사용되고 있었는데 로그아웃은 공통처리라서 CommonAuthService 만들어서 처리했습니다.
- createTokenService 에서 이미 만료된 refreshToken 의 경우에는 fcmToken null 처리만 해줬습니다.
=> 로그아웃 기능 구현

src/main/java/hous/server/domain/room/Participate.java, src/main/java/hous/server/domain/user/Onboarding.java, src/main/java/hous/server/domain/user/TestScore.java, src/main/java/hous/server/service/home/HomeRetrieveService.java, src/main/java/hous/server/service/room/RoomService.java, src/main/java/hous/server/service/slack/SlackService.java, src/main/java/hous/server/service/todo/TodoRetrieveService.java, src/main/java/hous/server/service/todo/TodoServiceUtils.java, src/main/java/hous/server/service/user/UserService.java, src/main/java/hous/server/service/user/UserServiceUtils.java
- Closes #164
1. 성향 테스트에 한번이라도 참여한 사람들의 순서를 고정시키기 위해 인덱스를 추가하기보다는 createdAt 으로 비교하는게 맞다고 생각해서 다시 기존처럼 null 처리 하는 방식으로 수정했습니다.
2. 클래스에 Comparable implement 해서 성향테스트 참여한 사람은 앞으로, 안한 사람은 뒤로 정렬되도록 했고
3. 본인을 맨 앞으로 빼는 로직은 유틸화해서 처리했습니다!
4. 슬랙 메시지 관련해서 @Profile 은 관련 환경일 때만 Bean 으로 등록하게 하는 어노테이션인데 SlackService 를 ControllerExceptionAdvice 에서 사용중이라 @Value 사용해서 prod 환경일 때만 사용하도록 수정해뒀습니다!
- 와다다다 하긴 했는데.. 수정 필요한 부분이나 더 좋은 의견 제시해주세용 하핳
=> 호미 정렬, 슬랙 메시지 prod 환경에서만 오도록 수정

src/main/java/hous/server/common/success/SuccessCode.java, src/main/java/hous/server/controller/user/UserController.java, src/main/java/hous/server/service/user/UserService.java, src/main/java/hous/server/service/user/UserServiceUtils.java, src/main/java/hous/server/service/user/dto/response/UpdatePersonalityColorResponse.java
- Closes #185
1. 성향 테스트 시 수정 성공 response와 함께 변경된 Personality color 전달하도록 수정하였습니다.
- 기존에는 성향 테스트 시 새 값으로 변경까지만 했는데 color를 전달하도록 수정했습니다.
- 클라에서 테스트 후 바로 결과 화면을 보여줘야 하는데 그러려면 `GET /user/personality/test` 요청을 보내려면 color 값이 필요해서요!
- 그런데 ... 지금 생각해보니 이렇게 되면 클라가 API 요청을 또 보내셔야 하는데 .... 
- 뭔가 API 요청을 적게 보낼 수 있도록 return 시 특정 컬러의 결과 조회에 담기는 모든 값을 보내달라고 할 것 같기도 합니다만 ..... 어떻게 생각하시나요 ?! 그렇게 변경할까요 ... ?
-> _**클라와 얘기해봤는데 테스트 후 바로 결과창으로 넘어가는 flow가 맞다고 하여 변경된 personlity의 정보를 전달해주는 형태로 변경했습니다.**_
->**아요와 안드가 재논의한 결과 put따로 get 따로요청한다고 하여 color 값만 추가하겠습니다**
=> 성향 테스트 시 수정 성공 response와 함께 변경된 Personality color 전달하도록 수정

src/main/java/hous/server/service/home/HomeRetrieveService.java, src/main/java/hous/server/service/home/dto/response/HomeInfoResponse.java
- Closes #193 
1. 홈 화면 조회 요일 데이터 추가
- 요일별 로티 띄워주기 위해 필요한 요일 데이터 추가했습니다!
=> #193 [fix] 홈 화면 조회 요일 데이터 추가

src/main/java/hous/server/service/todo/TodoRetrieveService.java
- Closes #208
1.멤버별 조회 시 각 멤버의 요일별 규칙 리스트의 정렬 순서를 규칙 생성 시점으로 정렬하도록 수정
=> 멤버별 조회 정렬 수정

src/main/java/hous/server/domain/user/Onboarding.java
- Closes #220
1. Onboarding 테이블의 introduction 의 최대 길이를 저희 정해놓은 컨벤션에 맞춰 40이 아니라 100으로 수정했답니다.
=> #220 [fix] 온보딩 introduction 필드 수정

src/main/java/hous/server/controller/user/UserController.java, src/main/java/hous/server/controller/user/UserRetrieveController.java, src/main/java/hous/server/domain/user/Onboarding.java
- Closes #222
1. 사용자 정보 조회 시, 404 방에 참여하지 않음 예외가 빠져있어서 명세서에 추가했습니다.
2. 사용자 정보 수정 시, 자기소개에서 \n 입력 시 공백으로 치환하여 저장하도록 수정했습니다.
=> [fix] 자기소개에서 \n 입력 시 공백으로 치환하여 저장하도록 수정

src/main/java/hous/server/controller/rule/RuleController.java, src/main/java/hous/server/service/rule/RuleService.java, src/main/java/hous/server/service/todo/TodoRetrieveService.java
- Closes #235
1. 멤버별 조회 시 todo Cnt 개수 수정
- 기존에는 멤버의 요일별 todo 수를 모두 더해  총 n개로 보내줬는데 해당 부분을 변경했습니다. 
- 각 멤버가 맡은 todo 수를 총 n개로 보내주도록 수정했습니다.
- 마지막 커밋만 봐주세용
=> #235 [fix] 멤버별 조회 시 todo Cnt 개수 수정

src/main/java/hous/server/service/home/HomeRetrieveService.java, src/main/java/hous/server/service/todo/TodoRetrieveService.java, src/main/java/hous/server/service/todo/dto/response/OurTodo.java, src/main/java/hous/server/service/todo/dto/response/OurTodoInfo.java
- Closes #238
1. ourtodo 가공 시 기존에는 투두가 생성된 시간순으로만 정렬을 했었는데 이름에 정렬순서를 수정했습니다.
=> #238 [fix] ourtodoinfo 가공 시 sorted(Onboarding::compareTo) 추가

src/main/java/hous/server/service/home/HomeRetrieveService.java, src/main/java/hous/server/service/todo/TodoRetrieveService.java, src/main/java/hous/server/service/todo/dto/response/OurTodo.java, src/main/java/hous/server/service/todo/dto/response/OurTodoInfo.java
- Closes #240
1. 요일별 조회 시 OurTodo에 todoId를 넘겨주도록 수정
2. OurTodoInfo extends OurTodo 상속하던거 제거
=> #240 [fix] 요일별 조회 시 OurTodo에 todoId를 넘겨주도록 수정

src/main/java/hous/server/common/exception/ErrorCode.java, src/main/java/hous/server/controller/rule/RuleController.java, src/main/java/hous/server/controller/todo/TodoController.java, src/main/java/hous/server/service/rule/RuleService.java, src/main/java/hous/server/service/rule/RuleServiceUtils.java, src/main/java/hous/server/service/todo/TodoService.java, src/main/java/hous/server/service/todo/TodoServiceUtils.java
- Closes #244
1. 규칙 추가/수정 시 이미 존재하는 name인 경우 409를 던지도록 utils 함수 추가 및 API 명세서 수정
2. todo 추가/수정 시 이미 존재하는 name인 경우 409를 던지도록 utils 함수 추가 및 API 명세서 수정
=> 규칙, todo 추가/수정 시 이미 존재하는 name인 경우 409를 던지도록 수정

src/main/java/hous/server/service/todo/TodoService.java, src/main/java/hous/server/service/todo/TodoServiceUtils.java
- Closes #254
1. todo 수정시 수정하는 todo 제외하고 이름 검사하도록 수정
=> #254 [fix] todo 수정시 수정하는 todo 제외하고 이름 검사하도록 수정

src/main/java/hous/server/common/success/SuccessCode.java, src/main/java/hous/server/config/interceptor/version/VersionCheckHandler.java, src/main/java/hous/server/controller/version/VersionRetrieveController.java, src/main/java/hous/server/domain/deploy/Deploy.java, src/main/java/hous/server/service/version/VersionRetrieveService.java, src/main/java/hous/server/service/version/VersionServiceUtils.java, src/main/java/hous/server/service/version/dto/response/VersionInfoResponse.java
- Closes #258
1. 강제 업데이트 여부 조회 관련 api 구현
2. 기존에 @Version에서 사용하던 메서드들을 공통적으로 사용할 것 같아서 Util 파일로 리팩터링했습니다!
3. Deploy 테이블에 market_url 칼럼 추가
- market_url 은 안드측 요청으로 추가했습니다! 마켓 링크도 같이 보내줬으면 좋겠다고 해서요!
- 관련 쿼리 노션에 반영해뒀습니다.
=> #258 [feat] 강제 업데이트 관련 api 구현

build.gradle, src/main/java/hous/server/config/swagger/SwaggerConfig.java, src/main/java/hous/server/domain/user/Onboarding.java, src/main/java/hous/server/service/room/RoomService.java
- Closes #278
1. 빌드될 때 이름 1.0.2 스냅샷으로 되도록 수정
2. 방 퇴사 시 알림 목록 삭제하는 로직 수정
- jpa 사용 안하고 더티체킹으로 삭제가 되더라구요 ! (확인 완료)
=> 방 퇴사 시 알림 목록 삭제하는 로직 수정

src/main/java/hous/server/common/exception/ErrorCode.java, src/main/java/hous/server/common/util/DateUtils.java, src/main/java/hous/server/controller/auth/AuthController.java, src/main/java/hous/server/controller/auth/dto/request/SignUpRequestDto.java, src/main/java/hous/server/controller/user/UserController.java, src/main/java/hous/server/domain/user/Onboarding.java, src/main/java/hous/server/domain/user/repository/UserRepositoryCustom.java, src/main/java/hous/server/domain/user/repository/UserRepositoryImpl.java, src/main/java/hous/server/service/auth/dto/request/SignUpDto.java, src/main/java/hous/server/service/user/UserScheduledService.java, src/main/java/hous/server/service/user/UserService.java, src/main/java/hous/server/service/user/UserServiceUtils.java, src/main/java/hous/server/service/user/dto/request/CreateUserRequestDto.java, src/main/java/hous/server/service/user/dto/request/UpdateUserInfoRequestDto.java, src/main/java/hous/server/service/user/dto/response/UserInfoResponse.java
- Closes #283
1. Onboarding 엔티티 birthday 데이터타입 LocalDate -> String
- 생년월일을 생략하는 경우 ""로 클라에서 보내신다고 하셔서 String으로 수정했습니다. **괜찮나요?!** (기존에 nullable = false 였길래요!)
- 기존 형태(LocalDate) 유지하고 nuallble = true로 수정하려고 했는데 
- 안드한테 물어보니까 어차피 String 형태로 주고 있고, 기존에도 LocalDate -> String 형태로 박는거였어서 String 으로 변경함!
2. 회원가입 시  birthday optional 반영 (`birthday="", isPublic=false`)
- `birthday="", isPublic=true`이면 400 에러 던집니다.
3. 프로필 정보 수정 시 birthday optional 반영 (`birthday="", isPublic=false`)
4. 나/룸메이트 조회 시 생년월일이 없는 경우 빈 스트링 보내도록 response 수정
5. 호미의 탄생 배지 스케줄러 돌릴 때 엔티티 데이터 타입 변경으로 DateUtils 에 `오늘날짜.toString()` 하는 함수 만들어서 수정
- 나/룸메이트 조회 시 age, birthday 부분이 없는 경우
-  "" 또는 null로 전달해주는게 의진오빠가 더 편하다고 해서 호옥시 안드는 null 처리를 안했을까봐 ""로 수정했습니다!
=> 전체적으로 생년월일 optional 하게 처리하도록 수정

src/main/java/hous/server/domain/todo/repository/DoneRepositoryImpl.java
- Closes #289
1. 모든 takes를 가져와서 done의 개수를 체크하는 부분을 오늘 날짜의 takes를 이용하도록 변경했습니다.
- 예를 들어 '혜정 월수금, 혁준 화목토' todo가 있는데 take는 2지만, 오늘 날짜의 take는 1임
- takes.size()와 done 개수로 체크 상태 (EMPTY, FULL, FULL_CHECK)를 구분해서 이렇게 변경함
- 스웨거로 확인함요 ㅠ 
```json
{
"status": 200,
"success": true,
"message": "todo 메인 페이지 조회 성공입니다.",
"data": {
"date": "12.28",
"dayOfWeek": "WEDNESDAY",
"progress": 66,
"myTodosCnt": 3,
"ourTodosCnt": 3,
"myTodos": [
{
"todoId": 1,
"todoName": "청소기 돌리기",
"isChecked": true
},
{
"todoId": 2,
"todoName": "빨래 개기",
"isChecked": true
},
{
"todoId": 3,
"todoName": "둘 다 할 일",
"isChecked": true
}
],
"ourTodos": [
{
"todoName": "청소기 돌리기",
"nicknames": [
"혜조니"
],
"status": "FULL_CHECK"
},
{
"todoName": "빨래 개기",
"nicknames": [
"혜조니",
"혁돌이"
],
"status": "FULL_CHECK"
},
{
"todoName": "둘 다 할 일", …
```
=> #289 [!HOTFIX] todo 메인 조회 시 ourTodo의 체크 상태 이슈 해결

src/main/java/hous/server/ServerApplication.java, src/main/java/hous/server/common/aspect/duplicate/PreventDuplicateRequest.java, src/main/java/hous/server/common/aspect/duplicate/RequestAspect.java, src/main/java/hous/server/common/aspect/logging/LoggingAspect.java, src/main/java/hous/server/common/aspect/logging/RequestLoggingAspect.java, src/main/java/hous/server/controller/auth/AuthController.java, src/main/java/hous/server/controller/room/RoomController.java, src/main/java/hous/server/controller/rule/RuleController.java, src/main/java/hous/server/controller/todo/TodoController.java, src/main/java/hous/server/controller/user/UserController.java
- Closes #292
1.  controller 메소드 실행 시점에 모든 요청에 대하여 request 내용 log 기록하기
2. response  내용 log 기록하기 추가
- 처음에 `@AfterReturning` 을 이용해서 200 성공한 데이터들만 info에 담으려고 했으나 
-`@Around` 어노테이션의 경우 포인트 컷으로 걸어놓은 **메소드 시작 시점 ~ 끝나는 시점**까지 모두 읽혀서 이 안에서 동작하도록 변경했습니다. 
- [이 블로그](https://pgnt.tistory.com/103) 보시면 실행 시점마다 로그 찍으신게 있는데 보시면 알 수 있음! 
info.log
```
[2023-01-29 23:35:37:75650] [32m[http-nio-8080-exec-1][0;39m [34mINFO [0;39m [1;37m[hous.server.common.aspect.logging.LoggingAspect.requestLogging:[33m32[0;39m][0;39m - ====> Request: POST http://localhost:8080/v1/auth/login/force (2ms)
*Header = {sec-fetch-mode=cors, content-length=188, referer=http://localhost:8080/swagger-ui.html, sec-fetch-site=same-origin, accept-language=ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7, origin=http://localhost:8080, …
```
=>  controller 메소드 실행 시점에 모든 요청에 대하여 request 내용 log 기록하기

src/main/java/hous/server/domain/badge/BadgeCounter.java, src/main/java/hous/server/domain/badge/BadgeCounterType.java, src/main/java/hous/server/domain/badge/mongo/BadgeCounterRepository.java, src/main/java/hous/server/service/rule/RuleService.java, src/main/java/hous/server/service/todo/TodoScheduledService.java, src/main/java/hous/server/service/user/UserService.java, src/main/java/hous/server/service/user/dto/request/UpdateTestScoreRequestDto.java, src/test/java/hous/server/service/badge/BadgeServiceTest.java, src/test/java/hous/server/service/badge/BadgeServiceUtilsTest.java, src/test/java/hous/server/service/todo/TodoServiceTest.java
- Closes #304
1. BadgeServiceUtils, BadgeService 테스트 코드 추가 후 테스트 수행
2. 기존 redis 에서 카운터 하는 로직 삭제
3. badgeCounter entity 수정
- 기존에는 ~CompleteCount 라는 필드명을 가졌는데 확장성을 고려하여 countType / count 로 변경했습니다.
4. 배지 획득 시 카운트 하는 로직 badgeCounter로 수정
- 수정 후 테스트 코드 변경하여 수행
- 우선 todo 관련 배지 중 스케줄러에 의해 획득되는 배지는 테스트가 어려운 상황입니다. (참 잘했어요, 성실왕 호미, 투두 마스터)
- 체크를 월 / 화 / 수 / 목 / 금 / 토 / 일 을 모두 해주고, 스케줄러 함수를 7번, 14번, 21번 호출하는 식으로 테스트 하려고 했으나
- 체크 내부 로직에서 오늘 날짜만 체크할 수 있도록 되어 있어서 테스트가 어려웠습니다 ..... 
- 이 부분은 논의가 필요해 보이네요 ... ㅠㅛㅠ 좋은 방법이 있다면 말해주세요 .... 
- 아쉬운대로 다른 카운트하여 획득하는 배지 (나도 날 잘 모르겠어, 우리집 기둥 호미) 미획득 시에 카운터 값을 확인하는 테스트 코드를 추가했습니다. 
- 기존에 카운터 로직의 if-else-if-else의 늪을 빠져나오고자 .... 로직을 변경하려고 했는데 잘 안되네요 ... 좋은 방법이 있다면 ..... 코리 부탁드립니다. .. ㅎㅎ
=> 배지 관련 데이터 mongoDB 적용하는 방식으로 로직 수정

hous-api/src/main/java/hous/api/controller/delete/MigrationController.java, hous-api/src/main/java/hous/api/service/delete/MigrationService.java, hous-api/src/main/java/hous/api/service/notification/dto/response/NotificationInfo.java, hous-api/src/test/java/hous/api/service/migration/MigrationDataTest.java, hous-common/src/main/java/hous/common/util/DateUtils.java, hous-core/src/main/java/hous/core/domain/common/AuditingTimeEntity.java, hous-core/src/main/java/hous/core/domain/delete/RdbNotification.java, hous-core/src/main/java/hous/core/domain/delete/mysql/RdbNotificationRepository.java, hous-core/src/main/java/hous/core/domain/notification/Notification.java
- Closes #315 
1. 알림 및 배지 카운터 데이터를 mongodb로 마이그레이션 하는 일회성 api 추가
2. 추후 삭제가 필요한 부분에 TODO 주석을 추가
- redis 데이터의 경우 테스트코드를 작성해서 정상적으로 전환되는 것을 확인했습니다.
- 알림 데이터의 경우 경우 현재 dev 서버에 이는 notification 데이터의 일부에 createAt을 변경하여 데이터를 전환하는 테스트를 진행했습니다.
=> 알림 및 배지 카운터 데이터를 mongodb로 마이그레이션 하는 일회성 api 추가
